AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.1 # Keep this in sync with chefs packaged ruby version

Layout/ClassStructure:
  Enabled: true

# I keep the length as short as possible without having too much pain.
# 80 is too much pain, but many disagree.
Layout/LineLength:
  Max: 100

# The trailing comma prevents brain cells from dying on copy-paste errors.
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Top-level class documentation is nice, but cumbersome when starting a new project.
Style/Documentation:
  Enabled: false

# Questionable, to say the least. Abandoned for Ruby 3 and then unknown.
Style/FrozenStringLiteralComment:
  Enabled: false

# App ids for MAS are easier to google and copy-paste if kept together.
Style/NumericLiterals:
  Enabled: false
