include_recipe 'macos::chrome'
include_recipe 'macos::diagnostics'
include_recipe 'macos::finder'
include_recipe 'macos::locate'
include_recipe 'macos::restrictions'
include_recipe 'macos::ssh'
include_recipe 'macos::xcode'
