include_recipe 'macos::chrome'
include_recipe 'macos::diagnostics'
include_recipe 'macos::dock'
include_recipe 'macos::safari'
include_recipe 'macos::spotlight'
include_recipe 'macos::ssh'
include_recipe 'macos::xcode'
