default[:apps][:vscode_extensions] = %w[
  aeschli.vscode-css-formatter
  aliariff.auto-add-brackets
  anjali.clipboard-history
  britesnow.vscode-toggle-quotes
  coenraads.bracket-pair-colorizer-2
  dae.vscode-refresh-browser
  dotjoshjohnson.xml
  eamodio.gitlens
  mikeburgh.xml-format
  ms-vsliveshare.vsliveshare
  patbenatar.advanced-new-file
  rebornix.ruby
  sianglim.slim
  syler.sass-indented
  viktorzetterstrom.non-breaking-space-highlighter
  wenfang.faster-new
  wingrunr21.vscode-ruby
]
